"""User facing API for solvemail

Docs: https://AnswerDotAI.github.io/solvemail/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['Gmail', 'Email', 'Emails', 'hsize', 'EmailAttachment', 'Draft', 'Drafts', 'Thread', 'Threads', 'Label']

# %% ../nbs/00_core.ipynb #fe46425b
from bs4 import BeautifulSoup
from email.utils import parsedate_to_datetime
from fastcore.all import *
from fastgws import GMail
from fastgws.auth import *
from .email import *

import asyncio,html,httpx,mistletoe,sys

# %% ../nbs/00_core.ipynb #da884c81
class Gmail:
    def __init__(self, creds, user_id='me'):
        self.client = GMail(creds=creds)
        self.user_id = user_id

    async def profile(self):
        "Profile resource with `email` attribute"
        d = await self.client.users.get_profile(user_id=self.user_id)
        return AttrDict(d, email=d.emailAddress)

# %% ../nbs/00_core.ipynb #9563f05e
def _flat_hdrs(d):
    if 'payload' not in d: raise ValueError("no headers: use format 'metadata' or 'full'")
    keep = {'date','from','to','subject','message-id','references',
            'reply-to','list-unsubscribe','list-unsubscribe-post'}
    hdrs = {x['name'].lower(): x['value'] for x in d.payload.headers if x['name'].lower() in keep}
    if 'from' in hdrs: hdrs['frm'] = hdrs.pop('from')
    if 'subject' in hdrs: hdrs['subj'] = hdrs.pop('subject')
    if 'message-id' in hdrs: hdrs['rfcid'] = hdrs.pop('message-id')
    d.update(hdrs)
    return d

def _has_att(e): return e.payload.get('mimeType')=='multipart/mixed'

class Email(AttrDict):
    def __init__(self, gmail, d):
        super().__init__(d)
        self.gmail = gmail

    def __repr__(self):
        if 'payload' not in self: return f'Email({self.id})'
        lbls = ','.join(self.get('labelIds') or [])
        att = '📎' if _has_att(self) else ''
        snip = html.unescape(self.get('snippet') or '')
        return f'Email({self.id}: [{lbls}] {att}{self.get("frm", "")} | {self.get("subj", "")}\n{snip})'

    async def refresh(self, fmt='metadata'):
        d = await self.gmail.client.users.messages.get(user_id='me', id=self.id, format=fmt)
        self.update(_flat_hdrs(d))
        return self

    @classmethod
    async def fetch(cls, gmail, id): return await cls(gmail, dict(id=id)).refresh('metadata')

# %% ../nbs/00_core.ipynb #353d1436
@patch
@delegates(mk_email)
async def send(self:Gmail, thread_id=None, **kwargs):
    sys.audit('solvemail.Gmail.send', kwargs.get('to'), kwargs.get('body'))
    msg = dict(raw=raw_email(mk_email(**kwargs)))
    if thread_id: msg['thread_id'] = thread_id
    return Email(self, await self.client.users.messages.send(user_id=self.user_id, **msg))

# %% ../nbs/00_core.ipynb #4a7fd890
@patch(as_prop=True)
async def text(self:Email):
    if 'payload' not in self or 'parts' not in self.payload: await self.refresh('full')
    return txt_part(self.payload)

# %% ../nbs/00_core.ipynb #6344fe31
def _clean_html(h):
    "Strip Gmail signatures and reply quotes from html `h`"
    soup = BeautifulSoup(h, 'html.parser')
    for sig in soup.select('.gmail_signature, .gmail_signature_prefix'): sig.decompose()
    for q in soup.select('.gmail_quote'):
        prev = q.find_previous_sibling()
        if prev and prev.get_text(strip=True): q.decompose()
    return str(soup)

@patch
async def html(self:Email, clean=True):
    if 'payload' not in self or 'parts' not in self.payload: await self.refresh('full')
    h = html_part(self.payload)
    return _clean_html(h) if h and clean else h

# %% ../nbs/00_core.ipynb #d0554d5f
@patch
async def body(self:Email, clean=True):
    soup = BeautifulSoup(await self.html(clean), 'html.parser')
    for br in soup.find_all('br'): br.replace_with('\n')
    for tag in soup.find_all(['p','div']): tag.append('\n')
    return re.sub(r'\n{3,}', '\n\n', soup.get_text().strip())

# %% ../nbs/00_core.ipynb #2d474ef0
def _email_row(e, att=None):
    att = _has_att(e) if att is None else att
    return f'| {e.id} | {e.frm or ""} | {e.get("subj") or ""} | {"📎" if att else ""} | {e.get("date") or ""} |'

_email_hdr = '| id | from | subj | 📎 | date |\n|-|-|-|-|-|\n'
class Emails(L):
    def __init__(self, d, *rest, gmail=None, **kwargs):
        super().__init__(d, *rest, **kwargs)
        self.gmail = gmail

    def _repr_markdown_(self): return _email_hdr + '\n'.join(self.map(_email_row))

    async def refresh(self, fmt='metadata'):
        if not self: return self
        reqs = [(e.id, self.gmail.client._gservice.users().messages().get(userId='me', id=e.id, format=fmt)) for e in self]
        res = self.gmail.client.batch_get(reqs)
        for e in self:
            d = res.get(e.id)
            if d: e.update(_flat_hdrs(dict2obj(d)))
        return self

@patch
async def _search(self:Gmail, rsrc, key, cls, coll, q=None, max_results=10, **kwargs):
    r = await getattr(self.client.users, rsrc).list(user_id=self.user_id, q=q, max_results=max_results, **kwargs)
    os = L(r.get(key) or []).map(lambda o: cls(self, o))
    return await coll(os, gmail=self).refresh()

@patch
async def search_emails(self:Gmail, q=None, max_results=20, **kwargs):
    return await self._search('messages', 'messages', Email, Emails, q, max_results, **kwargs)



# %% ../nbs/00_core.ipynb #2ecd04dc
def hsize(n):
    "Human-readable byte size"
    for u in ' KMGT':
        if n < 1024: return f'{n:.0f}{u.strip()}B' if u==' ' else f'{n:.1f}{u}B'
        n /= 1024
    return f'{n:.1f}PB'

class EmailAttachment(AttrDict):
    def __init__(self, gmail, mid, d):
        super().__init__(d)
        self.gmail = gmail
        self.mid = mid

    def __repr__(self): return f'EmailAttachment({self.filename!r}, {self.mimeType}, {hsize(self.body.size)})'

    async def fetch(self, save=None):
        r = await self.gmail.client.users.messages.attachments.get( user_id='me', message_id=self.mid,
                                                                    id=self.body.attachmentId)
        data = b64d(r.data)
        if save:
            p = Path(save)
            if p.is_dir(): p = p/self.filename
            p.write_bytes(data)
        return data

@patch(as_prop=True)
async def attachments(self:Email):
    if 'parts' not in self.payload: await self.refresh('full')
    return att_parts(self.payload).map(lambda a: EmailAttachment(self.gmail, self.id, a))

# %% ../nbs/00_core.ipynb #bd09ef81
@patch
async def delete(self:Email):
    sys.audit('solvemail.Email.delete')
    return await self.gmail.client.users.messages.delete(user_id='me', id=self.id)

# %% ../nbs/00_core.ipynb #e0d020b1
class Draft(Email):
    def __init__(self, gmail, d):
        self.draft_id = d.get('id')
        super().__init__(gmail, d.get('message') or {})

    def __repr__(self): return f'Draft({self.draft_id}: ' + super().__repr__()[6:]

    async def refresh(self, fmt='metadata'):
        d = await self.gmail.client.users.drafts.get(user_id='me', id=self.draft_id, format=fmt)
        self.draft_id = d['id']
        self.update(_flat_hdrs(d.message))
        return self

    @classmethod
    async def fetch(cls, gmail, id): return await cls(gmail, dict(id=id)).refresh('metadata')

@patch
@delegates(mk_email)
async def create_draft(self:Gmail, thread_id=None, **kwargs):
    msg = dict(raw=raw_email(mk_email(**kwargs)))
    if thread_id: msg['thread_id'] = thread_id
    d = await self.client.users.drafts.create(user_id=self.user_id, message=msg)
    return await Draft(self, d).refresh('metadata')

# %% ../nbs/00_core.ipynb #6fa74f13
@patch
@delegates(mk_email)
async def update_draft(self:Draft, thread_id=None, **kwargs):
    defaults = {k: self[k] for k in ('to','subj','cc') if self.get(k)}
    msg = dict(raw=raw_email(mk_email(**{**defaults, **kwargs})))
    if thread_id or self.get('threadId'): msg['thread_id'] = thread_id or self.threadId
    d = await self.gmail.client.users.drafts.update(user_id='me', id=self.draft_id, message=msg)
    self.draft_id = d['id']
    return await self.refresh('metadata')

# %% ../nbs/00_core.ipynb #8e386292
def _draft_row(d): return f'| {d.draft_id} | {d.get("frm") or ""} | {d.get("subj") or ""} | {d.get("date") or ""} |'

_draft_hdr = '| draft_id | from | subj | date |\n|-|-|-|-|\n'
class Drafts(L):
    def __init__(self, d, *rest, gmail=None, **kwargs):
        super().__init__(d, *rest, **kwargs)
        self.gmail = gmail

    def _repr_markdown_(self): return _draft_hdr + '\n'.join(self.map(_draft_row))

    async def refresh(self, fmt='metadata'):
        if not self: return self
        reqs = [(d.draft_id, self.gmail.client._gservice.users().drafts().get(userId='me', id=d.draft_id, format=fmt)) for d in self]
        res = self.gmail.client.batch_get(reqs)
        for d in self:
            r = res.get(d.draft_id)
            if r:
                d.draft_id = r['id']
                d.update(_flat_hdrs(dict2obj(r['message'])))
        return self

@patch
async def search_drafts(self:Gmail, q=None, max_results=10, **kwargs):
    return await self._search('drafts', 'drafts', Draft, Drafts, q, max_results, **kwargs)

# %% ../nbs/00_core.ipynb #e0d2be45
@patch
async def send(self:Draft):
    sys.audit('solvemail.Draft.send')
    return Email(self.gmail, await self.gmail.client.users.drafts.send(user_id='me', id=self.draft_id))

# %% ../nbs/00_core.ipynb #bac9930b
def _reply_hdrs(m, me=None):
    "Compute reply headers from parent email `m` (pass `me` for reply-all cc)"
    subj = m.get('subj') or ''
    if not re.match(r'(?i)^re:', subj): subj = f'Re: {subj}'
    refs = ' '.join(filter(None, [m.get('references'), m.get('rfcid')]))
    to = m.get('reply-to') or m.get('frm')
    cc = None
    if me:
        cc = {a.strip() for a in f"{m.get('to','')},{m.get('cc','')}".split(',')
              if a.strip() and a.strip().lower() != me.lower()} - {to}
        cc = ','.join(cc) or None
    return dict(to=to, subj=subj, in_reply_to=m.get('rfcid'), refs=refs or None, cc=cc)

# %% ../nbs/00_core.ipynb #33058858
async def _reply_quote(e):
    "Build gmail_quote attribution + blockquote for replied-to email `e`"
    h = await e.html(clean=False) or f"<pre>{await e.text}</pre>"
    when = parsedate_to_datetime(e.get('date')).strftime('%a, %b %-d, %Y at %-I:%M %p')
    attrib = f"On {when} {html.escape(e.get('frm'))} wrote:"
    return (f'<div class="gmail_quote">{attrib}<br>'
            f'<blockquote class="gmail_quote" style="margin:0 0 0 .8ex;'
            f'border-left:1px solid #ccc;padding-left:1ex">{h}</blockquote></div>')

@patch
@delegates(mk_email, but=['to','subj','body','html','headers','cc'])
async def reply_draft(self:Email, body=None, html=None, reply_all=False, **kwargs):
    if 'payload' not in self: await self.refresh('metadata')
    me = (await self.gmail.profile()).email if reply_all else None
    rh = _reply_hdrs(self, me)
    hdrs = {k.replace('_','-'):v for k,v in dict(In_Reply_To=rh['in_reply_to'], References=rh['refs']).items() if v}
    new = html or (mistletoe.markdown(body) if body else '')
    html = new + await _reply_quote(self)
    msg = dict(raw=raw_email(mk_email(to=rh['to'], subj=rh['subj'], cc=rh['cc'],
                                      body=body or '', html=html, headers=hdrs, **kwargs)),
               thread_id=self.threadId)
    d = await self.gmail.client.users.drafts.create(user_id='me', message=msg)
    return await Draft(self.gmail, d).refresh('metadata')

@patch
@delegates(mk_email, but=['to','subj','headers'])
async def reply(self:Email, **kwargs): return await (await self.reply_draft(**kwargs)).send()

# %% ../nbs/00_core.ipynb #e437064d
class Thread(AttrDict):
    def __init__(self, gmail, d):
        super().__init__(d)
        self.gmail = gmail
        self._set_emails()

    def _set_emails(self):
        self.emails = Emails(L(self.get('messages') or []).map(lambda m: Email(self.gmail, _flat_hdrs(m))), gmail=self.gmail)

    def __repr__(self):
        if not self.emails: return f'Thread({self.id})'
        m = self.emails[-1]
        att = '📎' if any(e.payload.get('mimeType')=='multipart/mixed' for e in self.emails) else ''
        return f'Thread({self.id}: {len(self.emails)} emails, [{",".join(m.labelIds or [])}] {att}{m.frm} -> {m.to} | {m.subj})'
    def _repr_markdown_(self): return self.emails._repr_markdown_()

    async def refresh(self, fmt='metadata'):
        d = await self.gmail.client.users.threads.get(user_id='me', id=self.id, format=fmt)
        self.update(d)
        self._set_emails()
        return self

    @classmethod
    async def fetch(cls, gmail, id): return await cls(gmail, dict(id=id)).refresh('metadata')

    @property
    def labelIds(self): return list({l for e in self.emails for l in (e.labelIds or [])})

    @property
    async def attachments(self):
        atts = await asyncio.gather(*self.emails.map(lambda e: e.attachments))
        return L(a for es in atts for a in es)

# %% ../nbs/00_core.ipynb #e90616f7
@patch(as_prop=True)
def last(self:Thread): return self.emails[-1]

@patch
@delegates(mk_email, but=['to','subj','headers'])
async def reply_draft(self:Thread, **kwargs):
    dr = await self.last.reply_draft(**kwargs)
    await self.refresh('metadata')
    return dr

@patch
@delegates(mk_email, but=['to','subj','headers'])
async def reply(self:Thread, **kwargs):
    em = await self.last.reply(**kwargs)
    await self.refresh('metadata')
    return em

# %% ../nbs/00_core.ipynb #1fa3424e
def _thread_row(t): return _email_row(t.emails[-1], any(_has_att(e) for e in t.emails)) + f' {len(t.emails)} |'

_thread_hdr = _email_hdr.replace('|\n|-', '| emails |\n|-').replace('-|\n', '-|-|\n')
class Threads(L):
    def __init__(self, d, *rest, gmail=None, **kwargs):
        super().__init__(d, *rest, **kwargs)
        self.gmail = gmail

    def _repr_markdown_(self): return _thread_hdr + '\n'.join(self.map(_thread_row))

    async def refresh(self, fmt='metadata'):
        if not self: return self
        reqs = [(t.id, self.gmail.client._gservice.users().threads().get(userId='me', id=t.id, format=fmt)) for t in self]
        res = self.gmail.client.batch_get(reqs)
        for t in self:
            d = res.get(t.id)
            if d:
                t.update(dict2obj(d))
                t._set_emails()
        return self

@patch
async def search_threads(self:Gmail, q=None, max_results=10, **kwargs):
    return await self._search('threads', 'threads', Thread, Threads, q, max_results, **kwargs)

# %% ../nbs/00_core.ipynb #3650c674
async def _fwd_one(e):
    "Build (html_block, att_tuples) for one forwarded message `e`"
    hdr = (f"\n\n---------- Forwarded message ----------\n\n"
           f"**From:** {e.get('frm')}  \n**Date:** {e.get('date')}  \n"
           f"**Subject:** {e.get('subj')}  \n**To:** {e.get('to')}  \n")
    body = await e.html(clean=False) or f"<pre>{await e.text}</pre>"
    atts = await e.attachments
    tups = await asyncio.gather(*atts.map(lambda a: a.fetch()))
    return mistletoe.markdown(hdr) + body, [(a.filename, d, a.mimeType) for a,d in zip(atts,tups)]

@patch
@delegates(mk_email, but=['subj','html','att','headers'])
async def forward(self:Email, to, subj=None, body=None, att=None, **kwargs):
    if 'internalDate' not in self: await self.refresh('full')
    th = await Thread.fetch(self.gmail, self.threadId)
    ems = th.emails.sorted(lambda e: int(e.internalDate)).filter(lambda e: int(e.internalDate) <= int(self.internalDate))
    parts = await asyncio.gather(*ems.map(_fwd_one))
    html = (mistletoe.markdown(body) if body else '') + ''.join(h for h,_ in parts)
    att = list(att or []) + [a for _,fa in parts for a in fa]
    return await self.gmail.send(to=to, subj=subj or f"Fwd: {self.get('subj')}", body=body or '', html=html, att=att, **kwargs)

@patch
@delegates(Email.forward)
async def forward(self:Thread, **kwargs): return await self.last.forward(**kwargs)

# %% ../nbs/00_core.ipynb #15a23629
_sys_lbls = set('INBOX SPAM TRASH UNREAD STARRED IMPORTANT SENT DRAFT CHAT '
                'CATEGORY_FORUMS CATEGORY_UPDATES CATEGORY_PERSONAL '
                'CATEGORY_PROMOTIONS CATEGORY_SOCIAL'.split())
def _norm_lbl(l): return l.upper() if isinstance(l,str) and l.upper() in _sys_lbls else l

class Label(AttrDict):
    def __init__(self, gmail, d):
        super().__init__(d)
        self.gmail = gmail
    def __repr__(self): return f'Label({self.id}:{self.name})'
    @property
    def is_sys(self): return self.get('type')=='system' or self.id in _sys_lbls

    async def refresh(self):
        self.update(await self.gmail.client.users.labels.get(user_id='me', id=self.id))
        self.gmail._lbls = None
        return self
    async def delete(self):
        sys.audit('solvemail.Label.delete')
        await self.gmail.client.users.labels.delete(user_id='me', id=self.id)
        self.gmail._lbls = None
    async def patch(self, **kwargs):
        self.update(await self.gmail.client.users.labels.patch(user_id='me', id=self.id, **kwargs))
        self.gmail._lbls = None
        return self
    async def rename(self, name): return await self.patch(name=name)

@patch
async def labels(self:Gmail, refresh=False):
    if refresh or self._lbls is None:
        d = await self.client.users.labels.list(user_id=self.user_id)
        self._lbls = L(d.get('labels') or []).map(lambda o: Label(self, o))
    return self._lbls

@patch
async def label(self:Gmail, lbl, refresh=False):
    lbl = _norm_lbl(lbl)
    if isinstance(lbl, Label): return lbl
    lbls = await self.labels(refresh=refresh)
    d = {**{o.name:o for o in lbls}, **{o.id:o for o in lbls}}
    if lbl in d: return d[lbl]
    raise KeyError(f'Unknown label: {lbl}')

@patch
async def lbl_ids(self:Gmail, lbls):
    if lbls is None: return []
    async def _one(l):
        l = _norm_lbl(l)
        if isinstance(l, Label): return l.id
        if isinstance(l, str) and l in _sys_lbls: return l
        try: return (await self.label(l)).id
        except KeyError: return l
    ls = L(lbls) if is_listy(lbls) else L([lbls])
    return L(await asyncio.gather(*ls.map(_one))).filter().unique().items

@patch
async def create_label(self:Gmail, name):
    d = await self.client.users.labels.create(user_id=self.user_id, name=name)
    self._lbls = None
    return Label(self, d)

# %% ../nbs/00_core.ipynb #9ed8bac9
@patch
async def modify(self:Email, add=None, rm=None):
    return self.update(await self.gmail.client.users.messages.modify(
        user_id='me', id=self.id,
        add_label_ids=await self.gmail.lbl_ids(add),
        remove_label_ids=await self.gmail.lbl_ids(rm)))

@patch
async def modify(self:Thread, add=None, rm=None):
    await self.gmail.client.users.threads.modify(
        user_id='me', id=self.id,
        add_label_ids=await self.gmail.lbl_ids(add),
        remove_label_ids=await self.gmail.lbl_ids(rm))
    return await self.refresh()

# %% ../nbs/00_core.ipynb #120c0a48
@patch
async def find_labels(self:Gmail, term, regex=False):
    lbls = await self.labels()
    if regex: return lbls.filter(lambda o: re.search(term, o.name))
    return lbls.filter(lambda o: term.lower() in o.name.lower())

# %% ../nbs/00_core.ipynb #2f89132b
@patch(as_prop=True)
async def labels(self:Email):
    if 'labelIds' not in self: await self.refresh('metadata')
    return L(await asyncio.gather(*L(self.labelIds).map(self.gmail.label))).attrgot('name')

@patch(as_prop=True)
async def labels(self:Thread):
    return L(await asyncio.gather(*L(self.labelIds).map(self.gmail.label))).attrgot('name')

# %% ../nbs/00_core.ipynb #e1600ded
@patch
async def mark_read(self:(Email,Thread)):   return await self.modify(rm='UNREAD')
@patch
async def mark_unread(self:(Email,Thread)): return await self.modify(add='UNREAD')
@patch
async def star(self:(Email,Thread)):        return await self.modify(add='STARRED')
@patch
async def unstar(self:(Email,Thread)):      return await self.modify(rm='STARRED')
@patch
async def archive(self:(Email,Thread)):     return await self.modify(rm='INBOX')
@patch
async def inbox(self:(Email,Thread)):       return await self.modify(add='INBOX')

# %% ../nbs/00_core.ipynb #7bc49692
@patch
async def trash(self:Email):
    sys.audit('solvemail.Email.trash')
    return self.update(await self.gmail.client.users.messages.trash(user_id='me', id=self.id))
@patch
async def untrash(self:Email): return self.update(await self.gmail.client.users.messages.untrash(user_id='me', id=self.id))

@patch
async def trash(self:Thread):
    sys.audit('solvemail.Thread.trash')
    await self.gmail.client.users.threads.trash(user_id='me', id=self.id)
    return await self.refresh()
@patch
async def untrash(self:Thread):
    await self.gmail.client.users.threads.untrash(user_id='me', id=self.id)
    return await self.refresh()

# %% ../nbs/00_core.ipynb #5f900aa0
@patch
async def delete(self:Draft):
    sys.audit('solvemail.Draft.delete')
    return await self.gmail.client.users.drafts.delete(user_id='me', id=self.draft_id)

@patch
async def delete(self:Thread):
    sys.audit('solvemail.Thread.delete')
    return await self.gmail.client.users.threads.delete(user_id='me', id=self.id)

# %% ../nbs/00_core.ipynb #3cacd9da
@patch
async def batch_modify(self:Gmail, ids, add=None, rm=None):
    "Add/remove `add`/`rm` labels from all messages in `ids`"
    return await self.client.users.messages.batch_modify(
        user_id=self.user_id, ids=listify(ids),
        add_label_ids=await self.lbl_ids(add),
        remove_label_ids=await self.lbl_ids(rm))

@patch
async def batch_delete(self:Gmail, ids):
    sys.audit('solvemail.Gmail.batch_delete', listify(ids))
    return await self.client.users.messages.batch_delete(
        user_id=self.user_id, ids=listify(ids))

@patch
async def modify(self:Emails, add=None, rm=None):
    return await self.gmail.batch_modify(self.attrgot('id'), add, rm)

@patch
async def delete(self:Emails):
    return await self.gmail.batch_delete(self.attrgot('id'))

@patch
async def trash(self:Emails):       return await self.modify(add='TRASH')
@patch
async def untrash(self:Emails):     return await self.modify(rm='TRASH')
@patch
async def mark_read(self:Emails):   return await self.modify(rm='UNREAD')
@patch
async def mark_unread(self:Emails): return await self.modify(add='UNREAD')
@patch
async def star(self:Emails):        return await self.modify(add='STARRED')
@patch
async def unstar(self:Emails):      return await self.modify(rm='STARRED')
@patch
async def archive(self:Emails):     return await self.modify(rm='INBOX')

# %% ../nbs/00_core.ipynb #b4a4f6f0
def _parse_unsub(unsub, post=None):
    "Parse a List-Unsubscribe header into an action dict"
    if not unsub: return None
    for url in re.findall(r'<([^>]+)>', unsub):
        if url.startswith('mailto:'):
            addr,_,qs = url[7:].partition('?')
            subj = dict(p.split('=',1) for p in qs.split('&')).get('subject','unsubscribe') if qs else 'unsubscribe'
            return dict(kind='mailto', addr=addr, subj=subj)
        if url.startswith('http'):
            return dict(kind='http', url=url, post=post or 'List-Unsubscribe=One-Click')
    return None

# %% ../nbs/00_core.ipynb #47c21da4
@patch
async def unsubscribe(self:Email):
    "Unsubscribe via List-Unsubscribe header (mailto or HTTP one-click POST)"
    if 'payload' not in self: await self.refresh('metadata')
    act = _parse_unsub(self.get('list-unsubscribe'), self.get('list-unsubscribe-post'))
    if not act: return None
    if act['kind'] == 'mailto': return await self.gmail.send(to=act['addr'], subj=act['subj'], body='unsubscribe')
    return httpx.post(act['url'], content=act['post'],
                      headers={'Content-Type':'application/x-www-form-urlencoded'})

@patch
async def unsubscribe(self:Thread): return await self.last.unsubscribe()
